language: android
android:
  components:
  - build-tools-27.0.0
  - android-27
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-27