language: android
jdk: oraclejdk8
env:
    global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=armeabi-v7a
android:
    components:
      - build-tools-27.0.0
      - android-27
      - extra-android-support
      - extra-google-m2repository
      - sys-img-armeabi-v7a-android-27
      - extra-android-m2repository