language: android
jdk: oraclejdk8
cache:
  directories:
   - node_modules
sudo: false

android:
  components:
   - build-tools-27.0.0
   - android-27
   - extra-android-support
   - extra-google-m2repository
   - sys-img-armeabi-v7a-android-27
   - extra-android-m2repository

  licenses:
   - 'android-sdk-license-.+'
env:
  global:
  - ANDROID_TARGET=android-23
  - ANDROID_ABI=armeabi-v7a
